{
 "title": "cluster_overview_dashboard1.0.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "node_cpu_hz",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[$__rate_interval]))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "memory  usage by pods in $namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "(container_memory_usage_bytes)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "node_on",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "api_server_status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "namespaces_on",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs error",
   "type": "logs",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "cpu_namespace_cpu_pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "(container_cpu_usage_seconds_total)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate5m{} != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage Nodes",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes)by (instance)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FS Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum (node_filesystem_device_error) by (instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "POD_CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resource Memory per namespace",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace)",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Node CPU cluster",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "Resource Memory per pod",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 46 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "{{pod}} "
    }
   ]
  }
 ]
}