{
 "title": "my_dashbord_update_1.1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_cfs_periods_total",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alert cluster",
   "type": "alertlist",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "kube_service_info{pod=\"prometheus-operator-kube-state-metrics-6d5c4f65cc-fwjnw\"}"
    }
   ]
  },
  {
   "title": "Resource Memory per namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace)",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Logs error",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\" ,stream=\"stderr\"} "
    }
   ]
  },
  {
   "title": "Memory Usage Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes)by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Memory per namespace",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } }
 ]
}