{
 "title": "my dashbord -2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_cfs_periods_total",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kube_namespace_status_phase{pod=\"prometheus-operator-kube-state-metrics-6d5c4f65cc-fwjnw\"}"
    },
    {
     "expr": "apiserver_watch_events_total{namespace=\"default\"} * 2"
    }
   ]
  },
  {
   "title": "Alert cluster",
   "type": "alertlist",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "kube_service_info{pod=\"prometheus-operator-kube-state-metrics-6d5c4f65cc-fwjnw\"}"
    }
   ]
  },
  {
   "title": "Resource Memory per namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace)",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Memory Usage Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes)by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Memory per namespace",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } }
 ]
}