{
 "title": "Wordpress statistics dashboard",
 "description": "Wordpress statistics dashboard includes:\n - Top 5 pages\n - Top browsers\n - Top 10 Referring Sites\n - Top Engines\n - Total Visitors \n - Total Online Users\n - Total Visits\n - Top 10 Countries (Count Visitor)\n - Top 10 Countries (Hits)\n - Visit & Visitor in the last 10 days\n",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Pages",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT b.post_title as 'Post Title', sum(a.count) as Visits \nFROM wp_statistics_pages a, wp_posts b\nwhere a.id=b.ID \ngroup by a.id \norder by Visits desc\nlimit 5;"
    }
   ]
  },
  {
   "title": "Top Browsers",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select now() AS \"time\", \ncase \nwhen agent like 'Chrome' then 'Chrome'\nwhen agent like 'FireFox' then 'FireFox'\nwhen agent like 'Safari' then 'Safari'\nwhen agent like 'Samsung Internet' then 'Samsung Internet'\nwhen agent like 'Unknown' then 'Other'\nend\nagent, count(*) FROM wordpress.wp_statistics_useronline\nwhere agent in ('Chrome', 'FireFox', 'Safari', 'Samsung Internet', 'Unknown') group by agent;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) as 'Total Visitor' FROM hawarfql_wp588.wpl7_statistics_visitor;"
    }
   ]
  },
  {
   "title": "Top 10 Countries (Count Visitor)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT location, COUNT(location) AS count FROM hawarfql_wp588.wpl7_statistics_visitor where location not like '000' GROUP BY location ORDER BY count DESC limit 10;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as 'Online Users' FROM hawarfql_wp588.wpl7_statistics_useronline;"
    }
   ]
  },
  {
   "title": "Top 10 Countries (Hits)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT location, sum(hits) AS count FROM hawarfql_wp588.wpl7_statistics_visitor where location not like '000' GROUP BY location ORDER BY count DESC limit 10;"
    }
   ]
  },
  {
   "title": "Top 10 Referring Sites",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(referred, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-1)\n AS Domain,\n count(*) AS 'References Hits' \n FROM hawarfql_wp588.wpl7_statistics_visitor\n group by domain order by 'References Hits' desc limit 10;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(visit) as 'Total Visits' FROM wpl7_statistics_visit order by last_visit desc limit 15;\n"
    }
   ]
  },
  {
   "title": "Top Engines",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select now() AS \"time\", \ncase \nwhen engine like 'google' then 'Google'\nwhen engine like 'bing' then 'Bing'\nwhen engine like 'yahoo' then 'Yahoo!'\nend\nengine, \ncount(*) count FROM hawarfql_wp588.wpl7_statistics_search group by engine order by count desc;"
    }
   ]
  },
  {
   "title": "Visit & Visitor in the last 10 days",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  last_visit AS \"time\",\n  Visit\nFROM wpl7_statistics_visit\nWHERE\n  $__timeFilter(last_visit)\nORDER BY last_visit"
    },
    {
     "rawSql": "SELECT DATE(last_counter) as time, count(*) as Visitor FROM hawarfql_wp588.wpl7_statistics_visitor group by last_counter;"
    }
   ]
  }
 ]
}